{
    "name": "silicon-soldier-db",
    "services": {
        "lib-server": {
            "type": "php:custom",
            "via": "cli",
            "overrides": {
                "build": "./lando/php8.0.0RC2"
            }
        }
    },
    "tooling": {
        "composer": {
            "service": "lib-server",
            "description": "Run composer",
            "cmd": "composer"
        },
        "phpunit": {
            "service": "lib-server",
            "description": "Run PHPUnit",
            "cmd": "vendor/bin/phpunit"
        }
    }
}
